name: biograph-platform-interview
services:
  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: developer
      MINIO_ROOT_PASSWORD: strong_password
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"
